# Generated by Django 3.1.3 on 2020-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('capacity', models.PositiveIntegerField(default=32)),
                ('permission_level', models.IntegerField(choices=[(1, 'USER'), (2, 'VIP'), (3, 'GOLD_VIP'), (4, 'ADMIN')], default=1)),
                ('users_online', models.ManyToManyField(blank=True, related_name='rooms_user_in', to='client_app.Client')),
            ],
        ),
    ]
