# Generated by Django 3.1.3 on 2020-11-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='permission_level',
            field=models.IntegerField(choices=[(1, 'USER'), (2, 'VIP'), (3, 'GOLD_VIP'), (4, 'ADMIN')], default=1),
        ),
    ]
